# -*- coding: utf-8 -*-
"""StreamLit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mcyKVd7gIQq_KZK1wvVWxvLhfNptbd-
"""

import openpyxl
import streamlit as st
import pandas as pd

# Título da aplicação
st.title("Comparação de Arquivos Excel com Streamlit")

# Função para carregar arquivos
def carregar_arquivo(msg):
    st.write(msg)
    arquivo = st.file_uploader(msg, type=['xlsx'])
    if arquivo:
        df = pd.read_excel(arquivo)  # Lê o arquivo como DataFrame
        st.success(f"Arquivo carregado com sucesso!")
        return df
    else:
        st.warning("Nenhum arquivo carregado.")
        return None

# Carregar o primeiro arquivo
df1 = carregar_arquivo("Faça o upload do primeiro arquivo (Ex.: Base de Créditos):")

if df1 is not None:
    # Exibir o primeiro DataFrame
    st.subheader("Primeiro arquivo carregado:")
    st.write(df1)

    # Carregar o segundo arquivo
    df2 = carregar_arquivo("Faça o upload do segundo arquivo (Ex.: Base de Débitos):")

    if df2 is not None:
        # Exibir o segundo DataFrame
        st.subheader("Segundo arquivo carregado:")
        st.write(df2)

        # Verificar e processar as colunas
        if 'debito' in df2.columns and 'credito' in df1.columns:
            df2['teste'] = df2['debito'].isin(df1['credito'])

            # Exibir o DataFrame modificado
            st.subheader("Arquivo modificado com coluna 'teste':")
            st.write(df2)

            # Baixar o arquivo modificado
            st.subheader("Baixar arquivo processado:")
            st.download_button(
                label="Download do Excel processado",
                data=df2.to_excel(index=False, engine='openpyxl'),
                file_name="resultado.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        else:
            st.error("As colunas necessárias ('debito' ou 'credito') não estão presentes nos arquivos.")
    else:
        st.error("O segundo arquivo não foi carregado.")
else:
    st.error("O primeiro arquivo não foi carregado.")

